FROM ethereum/solc:0.8.11-alpine as build-deps

FROM node:16.13.0 as builder

WORKDIR /usr/src/app/work

COPY package*.json ./
COPY src ./src
COPY tsconfig*.json ./

RUN npm install -g npm && npm install --legacy-peer-deps


FROM rust:1.59 as foundy

COPY --from=build-deps /usr/local/bin/solc /usr/bin/solc
COPY --from=builder /usr/src/app/work /usr/src/app/work

WORKDIR /usr/src/app/work
COPY contracts/ ./contracts

WORKDIR /usr/src/app/work

COPY deployments ./deployments
COPY foundry.toml ./
COPY remappings.txt ./
COPY .gitmodules ./
COPY deployments.json ./

COPY lib/ ./lib
COPY hardhat.config.ts ./
COPY .git ./.git
COPY chainDeploy/ ./chainDeploy
COPY deploy/ ./deploy
COPY tasks/ ./tasks
COPY test/ ./test
COPY contracts/ ./contracts

RUN curl -L https://foundry.paradigm.xyz | bash
RUN ls $HOME/.foundry
RUN echo $(ls $HOME/.foundry/bin)

RUN mv /root/.foundry/bin/foundryup /usr/bin/
RUN  foundryup

RUN mv /root/.foundry/bin/forge /usr/bin/

RUN forge install
RUN forge build


FROM node:16.13.0

COPY --from=build-deps /usr/local/bin/solc /usr/bin/solc
COPY --from=foundy /usr/src/app/work /usr/src/app/work

WORKDIR /usr/src/app/work

RUN npm run typechain
RUN npm run build:sdk

COPY docker/*.sh ./

RUN chmod +x *.sh

ENTRYPOINT ["./hh-test.sh"]