FROM ethereum/solc:0.8.11-alpine as build-deps

FROM rust:1.59 as builder

WORKDIR /usr/src/app

COPY package*.json ./
COPY foundry.toml ./
COPY remappings.txt ./
COPY .gitmodules ./
COPY deployments.json ./
COPY tsconfig*.json ./
COPY lib/ ./lib
COPY hardhat.config.ts ./
COPY .git ./.git
COPY chainDeploy/ ./chainDeploy
COPY deploy/ ./deploy
COPY tasks/ ./tasks
COPY test/ ./test
COPY contracts/ ./contracts
COPY src ./src


RUN curl -L https://foundry.paradigm.xyz | bash
RUN ls $HOME/.foundry
RUN echo $(ls $HOME/.foundry/bin)

RUN mv /root/.foundry/bin/foundryup /usr/bin/
RUN  foundryup

RUN mv /root/.foundry/bin/forge /usr/bin/

RUN forge install
RUN forge build


FROM node:16.13

COPY --from=build-deps /usr/local/bin/solc /usr/bin/solc
COPY --from=builder /usr/src/app /usr/src/app

WORKDIR /usr/src/app

RUN npm install -g npm && npm install --legacy-peer-deps

RUN npm run typechain
RUN npm run build:sdk

COPY docker/hh-test.sh .
COPY docker/start-node.sh .
COPY docker/start-bsc-node.sh .

RUN chmod +x start-node.sh hh-test.sh start-bsc-node.sh

ENTRYPOINT ["./start-bsc-node.sh"]