name: Push - publish package

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-test-local:
    env:
      MNEMONIC: "${{ secrets.MNEMONIC }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build Dockerfile for tests
        run: docker build -t contracts -f Dockerfile.test .

      - name: Run tests
        run: docker run -t --env MNEMONIC="${MNEMONIC}" --entrypoint "./hh-test.sh" contracts

  build-and-test-local-forge:
    env:
      MNEMONIC: "${{ secrets.MNEMONIC }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Forge dependencies
        run: forge install

      - name: Install NPM packages
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run forge tests
        run: npm run test:forge

  release:
    needs:
      - build-and-test-local
#      - build-and-test-local-forge
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      MNEMONIC: "${{ secrets.MNEMONIC }}"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install
      - run: npm run build:hardhat
      - run: npm run build:sdk
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{env.GITHUB_REF_NAME == 'main' && 'latest' || 'beta'}}
          access: "public"
