name: Working Repo

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches: [main, development]

jobs:
  hh-test-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: npm run test

  hh-test-bsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: npm run test:bsc

  forge-test-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - run: npm install
      - run: npm run build
      - run: forge test -vvv

  e2e-liquidation-tests:
    runs-on: ubuntu-latest
    env:
      ETHEREUM_ADMIN_ACCOUNT: "${{ secrets.ETHEREUM_ADMIN_ACCOUNT }}"
      ETHEREUM_ADMIN_PRIVATE_KEY: "${{ secrets.ETHEREUM_ADMIN_PRIVATE_KEY }}"
      MNEMONIC: "${{ secrets.MNEMONIC }}"
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker pull ghcr.io/midas-protocol/fuse-liquidator-bot:main
          docker-compose up --build -d liquidation-bot e2e && \
          docker-compose run verify-liquidations && \
          docker-compose down

  release:
    needs: [hh-test-local]
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{env.GITHUB_REF_NAME == 'main' && 'latest' || env.GITHUB_REF_NAME == 'development' &&  'beta' || 'preview'}}
          access: "public"
